# Generated by Django 5.1.6 on 2025-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.CharField(choices=[('GOLD', 'Gold Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan'), ('CAR', 'Car Loan'), ('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan')], default='PERSONAL', max_length=50),
        ),
    ]
